package main

import "os"
import "fmt"
import "mapreduce"
import "strings"
import "strconv"
import "unicode"
import "sort"

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// Your code here (Part V).

	// 分词
	words := strings.FieldsFunc(value, func (c rune) bool {
		return !unicode.IsLetter(c)
	})

	// 输出所有单词和文件名
	kvList := make([]mapreduce.KeyValue, len(words))
	for i, word := range words {
		kvList[i] = mapreduce.KeyValue{word, document}
	}

	return kvList
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	// Your code here (Part V).

	// 去重
	newValues := removeDuplicate(values)
	
	// 排序
	sort.Strings(newValues)

	return strconv.Itoa(len(newValues)) + " " + strings.Join(newValues, ",")
}

func removeDuplicate(values []string) []string {
	setMap := map[string]bool{}
	newValues := make([]string, 0)

	for _, v := range values {
		if _, ok := setMap[v]; !ok {
			setMap[v] = true
			newValues = append(newValues, v)
		}
	}

	return newValues
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100, nil)
	}
}
